name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - seaborn
  - matplotlib.pyplot
  - pingouin
  - scikitplot
  - sklearn.preprocessing
  - sklearn.discriminant_analysis
  - sklearn.model_selection
  - sklearn.decomposition
  - sklearn.utils
  - mpl_toolkits.mplot3d
  - scipy.stats
  - sklearn.cluster
  - sklearn.metrics
