name: virtual_environment
channels:
  - conda-forge
dependencies:
  - python3
  - numpy
  - scipy
  - pandas
  - seaborn
  - matplotlib
  - pingouin
  - pip
  - pip:
    - scikitplot
    - sklearn
    - mpl_toolkits
